all:
	gcc -o my_cat my_cat.c 
	gcc -o my_ls my_ls.c
	gcc -o my_date my_date.c
	gcc -o my_rm my_rm.c
	gcc -o my_mkdir my_mkdir.c
	gcc -o shell shell.c
clean:
	rm my_mkdir my_rm my_date my_ls my_cat shell